DATA:
  RAW: "data/raw/"
  INGESTED: "data/processed/ingest_data/"
  COMPOSITE: "data/processed/create_composite/"
  TO_ANNOTATE: "data/processed/data_to_annotate/"
  ANNOTATED_MASKS: "data/processed/labkitinference/"
  ANNOTATED_DATASET: "data/processed/generate_annotated_dataset/"
  TRAINVAL_DATASET: "data/processed/prepare_dataset_for_openmmseg/"

MODELING_EXP: "data/processed/work_dirs"

FO_EVALUATIONS: "data/processed/fiftyone_evaluations"

EXPORT: "data/processed/exporter"

CREATE_TASKS:
  n_clusters: 15

LOCAL_EMBEDDING_CENTER:
  name: "embedding_centers_lot2"
  local_path: "data/processed/compute_embedding_filter_centers/embedding_centers_lot2.json"

